modLoader="javafml"
loaderVersion="[40,)"
license="Apache License 2.0"

[[mods]]
modId="log_un_spam"
version="${file.jarVersion}"
displayName="logUnSpam"
description='''
Filter spam from any mods.
'''

[[dependencies.log_un_spam]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.log_un_spam]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18)"
    ordering="NONE"
    side="BOTH"
